# Generated by Django 6.0 on 2025-12-19 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_enrollment_rename_active_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
